-- SELECT C.CUSTOMER_NUMBER
-- FROM ORDERS O
-- JOIN ORDERS C
-- ON C.CUSTOMER_NUMBER=O.ORDER_NUMBER
-- ORDER BY C.CUSTOMER_NUMBER DESC
-- LIMIT 1; 


SELECT CUSTOMER_NUMBER
FROM ORDERS
GROUP BY CUSTOMER_NUMBER
ORDER BY COUNT(*) DESC
LIMIT 1;

